# 托管的类包扫描路径
scanPackage=cn.gyw.handwritten.gspring.demo

templateRoot=layouts

# aop
# 切面表达式
aspect.pointCut=public * cn.gyw.handwritten.gspring.demo.service..*Service..*(.*)
# 切面类
aspect.class=cn.gyw.handwritten.gspring.demo.aspect.LogAspect
# 前置通知
aspect.before=before
# 后置通知
aspect.after=after
# 异常通知
aspect.afterThrow=afterThrowing
# 切面异常类型
aspect.exception.name=java.lang.Exception