inventory:
  product:
    url: http://localhost:9002/warehouse-product

datasource:
  host: localhost:3306

dubbo:
  address: zookeeper://127.0.0.1:2181
  cacheFile: D:/temp/Zookeeper/product-service.txt