# 模拟 Master 库
db.master.driverClassName=com.mysql.jdbc.Driver
db.master.url=jdbc:mysql://localhost:3306/mydb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
db.master.username=root
db.master.password=Cc555555

# 模拟 Slaver 库
db.slaver.driverClassName=com.mysql.jdbc.Driver
db.slaver.url=jdbc:mysql://localhost:3306/mydb_slaver1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
db.slaver.username=root
db.slaver.password=Cc555555