delimiter $$

create procedure sp_create_db ()
begin
	CREATE database IF NOT exists `db_001` CHARACTER SET utf8 COLLATE utf8_general_ci;
	use `db_001`;
	CREATE TABLE `log_01`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_02`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_03`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_04`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;

	CREATE database IF NOT exists `db_002` CHARACTER SET utf8 COLLATE utf8_general_ci;
	use `db_002`;
	CREATE TABLE `log_01`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_02`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_03`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_04`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	
	CREATE database IF NOT exists `db_003` CHARACTER SET utf8 COLLATE utf8_general_ci;
	use `db_003`;
	CREATE TABLE `log_01`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_02`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_03`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_04`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	
	CREATE database IF NOT exists `db_004` CHARACTER SET utf8 COLLATE utf8_general_ci;
	use `db_004`;
	CREATE TABLE `log_01`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_02`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_03`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	CREATE TABLE `log_04`(
	  log_id INT UNSIGNED NOT NULL COMMENT '流水日志ID',
	  modified_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后修改时间',
	) ENGINE = innodb;
	
end 

delimiter ;