# 开发环境
spring:
  profiles: dev
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/community_system?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    dbcp2:
      validation-query: select 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        show_sql: true