server:
  port: 9003

spring:
  profiles:
    active: default
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_order?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    dbcp2:
      validation-query: select 1
  # 热部署
  devtools:
    restart:
      enabled: true
      exclude: application.yml

mybatis:
  check-config-location: true                             # 是否检测MyBatis运行参数配置文件
  #config-location: classpath:/mybatis-config.xml          # 指定MyBatis运行参数配置文件位置
  mapper-locations: classpath:/mapper/**/*.xml            # 注册XML映射器
  #type-aliases-package: test.springboot.model             # 配置Java类型包名
  #type-handlers-package: test.springboot.handlers         # 配置类型处理器包名
  executor-type: SIMPLE                                   # 指定执行器类型
  configuration:
    default-fetch-size: 20
    default-statement-timeout: 30
    mapUnderscoreToCamelCase: true