# Mysql
driverClass=com.mysql.cj.jdbc.Driver
driverUrl=jdbc:mysql://localhost:3306/mybatis?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
username=root
password=Cc555555